name: av_pointage
description: "AVTRANS"
publish_to: 'none'
version: 0.0.8

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.0
  shared_preferences: ^2.2.2
  dartz: ^0.10.1
  equatable: ^2.0.5
  provider: ^6.1.2
  package_info_plus: ^8.0.0
  geolocator: ^13.0.2
  permission_handler: ^11.3.1
  image_picker: ^1.1.2
  table_calendar: ^3.1.2
  intl: ^0.20.2
  signature: ^6.3.0
  path_provider: ^2.1.2
  open_filex: ^4.4.0
  url_launcher: ^6.2.5
  file_picker: ^8.0.0
  webview_flutter: ^4.13.1
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "lib/assets/icons/icon-512x512.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "lib/assets/icons/icon-512x512.png"

flutter:
  uses-material-design: true
  assets:
    - .env
    - lib/assets/
    - lib/assets/icons/